site_name: base-learn-template Documentation
theme: 'material'
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - wikilinks
  - codehilite:
      linenums: True
extra:
  palette:
    primary: '#087da1'
    accent: '#00a889'
  font:
    text: 'Source Sans Pro'

repo_name: 'luismayta/base-learn-template'
repo_url: 'https://github.com/luismayta/base-learn-template'
copyright: 'Copyright © 2021 <a href="https://luismayta.dev">luismayta</a>'

google_analytics:
  - ''
  - 'auto'
